// Barrel — importa todo desde un solo lugar:
// import { HeroArtefacto, AboutSection, ... } from '@/components/artefacto';
export { default as LandingArtefacto } from './LandingArtefacto';
export { default as HeroArtefacto } from './HeroArtefacto';
export { default as Navbar } from './Navbar';
export { default as TransitionOverlay } from './TransitionOverlay';
export { default as ScrollTransition } from './ScrollTransition';
export { default as LogoRevealLoader } from './LogoRevealLoader';
export { default as MobileMenu } from './MobileMenu';
export { default as AnimatedReveal, SplitText } from './AnimatedReveal';
export * from './transitions';
export { default as AboutSection } from './AboutSection';
export { default as ConvocatoriaSection } from './ConvocatoriaSection';
export { default as CalendarSection } from './CalendarSection';
export { default as ContactSection } from './ContactSection';
export { default as Footer } from './Footer';
export { default as FooterParallax } from './FooterParallax';
export { default as GlobalParallaxSection } from './GlobalParallaxSection';
export { default as SectionHeader } from './SectionHeader';
export { default as ConoceMasSection } from './ConoceMasSection';
export { default as FullScreenBlock } from './FullScreenBlock';
export { default as TextBlock } from './TextBlock';
export { default as ImageBackgroundBlock } from './ImageBackgroundBlock';
export { default as ConvocatoriaBlock } from './ConvocatoriaBlock';
export { default as CronogramaBlock } from './CronogramaBlock';
export * from './theme';
